#ifndef QTGENTTECPRODEFINES_H
#define QTGENTTECPRODEFINES_H

#define QTGENTTECPRO_MAJOR_VERSION 0
#define QTGENTTECPRO_MINOR_VERSION 0
#define QTGENTTECPRO_PATCH_VERSION 0


#define DMX_PRO_HEADER_SIZE 4
#define DMX_PRO_START_MSG 0x7E
#define DMX_START_CODE 0
#define DMX_START_CODE_SIZE 1
#define DMX_PRO_SEND_PACKET 6 // "periodically send a DMX packet" mode
#define DMX_PRO_END_SIZE 1
#define DMX_PRO_END_MSG 0xE7
#define DMX_PRO_BAUDRATE 250000


#endif // QTGENTTECPRODEFINES_H

